#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# remove old case
./Allclean

# create blockMeshDict
m4 ./system/blockMeshDict.m4 > ./system/blockMeshDict
runApplication blockMesh

# refine mesh
runApplication topoSet -dict system/cRefine.topoSetDict
runApplication refineMesh -overwrite -dict system/refineMeshDict

# refine mesh 2
runApplication -s 2 topoSet -dict system/cRefine.topoSetDict
runApplication -s 2 refineMesh -overwrite -dict system/refineMeshDict

# BCs
rm -rf 0
cp -rf 0.orig 0

# initial inner fields
mapFields ../fullScaleBaseRefined/ -sourceTime latestTime -mapMethod mapNearest -targetRegion region0

# run
runApplication $(getApplication)

# postProcess
postProcess -func 'mag(U)' -latestTime
postProcess -func 'sampleDict' -latestTime
