#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# remove old case
./Allclean

# create blockMeshDict
m4 ./system/blockMeshDict.m4 > ./system/blockMeshDict
runApplication blockMesh

# BCs
rm -rf 0
cp -rf 0.orig 0

# run
runApplication $(getApplication)
# run in paralell
#runApplication decomposePar
#runParallel $(getApplication)

# postProcess
#postProcess -func 'mag(U)' -latestTime
#postProcess -func 'sampleDict' -latestTime

