#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
# Spill time variable
time=79
endTime=200
deltaT=1E0
deltaTAf=1E0

# remove old case
./Allclean

# create blockMeshDict
m4 ./system/blockMeshDict.m4 > ./system/blockMeshDict
runApplication blockMesh

# create source inlet patch
runApplication topoSet -dict system/topoSetDict
runApplication createPatch -overwrite

# BCs
rm -rf 0
cp 0.orig/T.fixedTemGround 0.orig/T
cp -rf 0.orig 0

# initial inner fields
mapFields ../burro9Atm/ -sourceTime latestTime -mapMethod mapNearest -targetRegion region0

# run
cp system/controlDict.orig system/controlDict
foamDictionary -entry endTime -set "$time" system/controlDict
foamDictionary -entry deltaT -set "$deltaT" system/controlDict
runApplication -s gasRelease $(getApplication)
# run in paralell
#runApplication decomposePar
#runParallel $(getApplication)

# change bcs
foamDictionary -entry boundaryField.vapourInlet.value -set "uniform 0" $time/CH4
foamDictionary -entry boundaryField.vapourInlet.value -set "uniform 1" $time/air
foamDictionary -entry boundaryField.vapourInlet -set "{type noSlip;}" $time/U
foamDictionary -entry boundaryField.vapourInlet -set "{type zeroGradient;}" $time/T

# change endTime
foamDictionary -entry endTime -set "$endTime" system/controlDict
foamDictionary -entry deltaT -set "$deltaTAf" system/controlDict
runApplication -s afterRelease $(getApplication)

# postProcess
#postProcess -func 'mag(U)' -latestTime
#postProcess -func 'sampleDict' -latestTime

